# USER DIRECTIONS ------------------------------------------
# Update the following parameters for your analysis
# When complete, run this file by entering the following 
# command into the terminal:
# python fpho_config.py --config config.yml
# ----------------------------------------------------------

# REQUIRED INPUTS ------------------------------------------
#To import a new fiberphotometry data file, set True (otherwise False)
import_new: True

#  Name/file path for file containing fiberpho data from Bonsai (string)
input_filename: "Data/FiberPhoSig2021-05-28T10_46_57.csv"

# Name for output files including summary csv and plots 
# Do not include a file type (e.g. "my_file_name")
output_filename: "4030_4020"

# Column index for green 1 (int between 3 and 6)
f1greencol: 9

# Column index for green 1 (int between 3 and 6)
f1redcol: 5

#Column index for green 2 (int between 3 and 6) (enter 'None' if one fiber)
f2greencol: 10

# Column index for green 1 (int between 3 and 6) (enter 'None' if one fiber)
f2redcol: 6

#  Number of the animal corresponding to fluoresence data (int)
animal_ID: "4030_4020"

# Date of data collection (string, form: YYYY-MM-DD)           
exp_date: "2020-5-28"

# Brief explantation of experiment (string)
exp_desc: "Introductions"

##To reload data that's been previously analyzed
reload_data: False

#Summary files to import
reload_filenames: ["Data/4020_4030_Summary.csv"]

# To write an excel file of fiberpho data, set True (otherwise False)
write_xlsx: True

# To plot the raw signal trace, set True (otherwise False)
plot_raw_signal: True

# which channels are you interested in analyzing
# options [f1GreenGreen, f1GreenIso, f2GreenGreen, f2GreenIso, f1RedRed, f1RedIso, f2RedRed, f2RedIso] 
all_signals: [f1GreenGreen, f2GreenGreen]
 
#which channels will be used for motion correction for the above channels
# options [f1GreenGreen, f1GreenIso, f2GreenGreen, f2GreenIso, f1RedRed, f1RedIso, f2RedRed, f2RedIso] 
all_references: [f1GreenIso, f2GreenIso]

# To normalize your data using a reference and biexponential fits, set True (otherwise False)
normalize_data: False

# ----------------------------------------------------------

# BEHAVIOR ANALYSIS ----------------------------------------
# If not using, leave import as False and other fields empty

# To import behavior data, set True (otherwise False)
import_behavior: True

# Name/file path of BORIS file containing behavior data (string)
BORIS_file: "Data/10_46_57_boris_intro_fibers3&4.csv"

plot_behavior: False

# To plot the z-score analysis, set True (otherwise False)
plot_zscore: False

zscore_behs: ["Clap_Alone", "Clap_Together"]

fourier_transform: False

#------------------------------------------------------------

# SYNCHRONY ANALYSIS ----------------------------------------

#To run a pearson's correlation between two fibers from the same trial, set True (otherwise False)
within_trial_pearsons: False

# Add the pairs of channels you would like to compare in synchrony
channels: [[f1GreenGreen, f2GreenGreen]]

#To run a pearson's correlation between two fibers from the same trial only while animals are doing a specific behavior, set True (otherwise False)
behavior_specific_pearsons: False

#Add each behavior you would like to put through analysis, to combine two different behaviors add them to the same list
behaviors: [['together'], ['separate']]
